# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10XTYPyhfKCs2ZuvLx5RZR-gL9_UA_f7t
"""

#Phase 6 Dashboard
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.figure_factory as ff


# For Plotly visualizations in Dash
import plotly.graph_objects as go
import plotly.express as px
from dash import Dash, dcc, html, Input, Output, State # Corrected import of Dash class
import base64 # For embedding images
from dash import dash_table # Corrected import for dash_table

# For sentiment analysis and word cloud
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
from wordcloud import WordCloud
from nltk.corpus import stopwords
import io
import joblib # Import joblib for loading model performance data

# Download NLTK data safely (for Render deployment)
try:
    nltk.data.find('sentiment/vader_lexicon')
except LookupError:
    nltk.download('vader_lexicon')

try:
    nltk.data.find('corpora/stopwords')
except LookupError:
    nltk.download('stopwords')

# Helper function to find optimal threshold
def find_optimal_threshold(fpr, tpr, thresholds):
    optimal_threshold = None
    min_diff = float('inf')
    for i in range(len(thresholds)):
        sensitivity = tpr[i]
        specificity = 1 - fpr[i]
        diff = abs(sensitivity - specificity)
        if diff < min_diff:
            min_diff = diff
            optimal_threshold = thresholds[i]
    return optimal_threshold

# --- 2. Load and Preprocess Data (for EDA and KPIs) ---

# Using existing file paths from kernel state
file1 = pd.read_csv('customer profiles.csv')
file2 = pd.read_csv('customer info.csv')
file3 = pd.read_csv('customer details.csv')

# Merge 3 structured data sets and create a master data
customer_joined = pd.merge(file1, file2, on='custid', how='inner')
master_file = pd.merge(customer_joined, file3, on='custid', how='inner')

# Save to Excel and reload to simulate the notebook flow, ensuring clean start for processing
output_file_path = "master_file.xlsx"
master_file.to_excel(output_file_path, index=False)
data = pd.read_excel(output_file_path, sheet_name='Sheet1')

# Handle null values: replace None with NaN, then NaN with "NA"
data = data.replace({None: np.nan})
data = data.fillna("NA")

# Recoding numerical variables to categorical
data['gender'] = data['gender'].replace({1: 'F', 2: 'M'})
data['ms'] = data['ms'].replace({1: 'S', 2: 'M'})
data['veh'] = data['veh'].replace({1: 'N', 2: 'Y'})
data['house'] = data['house'].replace({1: 'N', 2: 'Y'})
data['selfemp'] = data['selfemp'].replace({1: 'N', 2: 'Y'})
data['account'] = data['account'].replace({1: 'N', 2: 'Y'})
data['deposit'] = data['deposit'].replace({1: 'N', 2: 'Y'})

# Convert child to categorical string representations
data['child'] = data['child'].replace({2: 'More than 1 child', 1: 'zero or 1 child'})

# Convert 'preloan' to string type before replacement and then to categorical
data['preloan'] = data['preloan'].astype(str)
data['preloan'] = data['preloan'].replace({'2': 'Not the First Loan', '1': 'First Loan', 'NA': np.nan}) # Handle 'NA' from fillna
data['preloan'] = pd.Categorical(data['preloan'])

# Create 'age_category_cut'
bins = [0, 1.5, 2.5, 3.5]
labels = ['Teenager', 'Adult', 'Senior Citizen']
data['age_category_cut'] = pd.cut(data['age'], bins=bins, labels=labels, right=True, include_lowest=True)

# Convert numeric columns that might have "NA" back to numeric, coercing errors
for col in ['debtinc', 'creddebt', 'othdebt']:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# Convert 'bad' column to numeric (0 or 1) and fillna if any introduced by previous steps
data['bad'] = data['bad'].replace({'Defaulter': 1, 'Non-Defaulter': 0})
data['bad'] = pd.to_numeric(data['bad'], errors='coerce')
data.dropna(subset=['bad'], inplace=True) # Drop rows where target variable is NaN
data['bad'] = data['bad'].astype(int)


# --- 3. Perform Data Analysis (EDA) ---

# Overall Bad Rate
overall_bad_rate = data['bad'].value_counts(normalize=True) * 100
fig_overall_bad_rate = px.pie(
    values=overall_bad_rate.values,
    names=['Non-Defaulter', 'Defaulter'],
    title='Overall Bad Rate',
    color_discrete_sequence=['blue', 'orange']
)

# Mean/Median of Debtinc by Bad
debtinc_stats = data.groupby('bad')['debtinc'].agg(['mean', 'median'])
fig_debtinc_stats = px.bar(
    debtinc_stats.reset_index(),
    x='bad', y=['mean', 'median'], barmode='group',
    title='Mean and Median of Debtinc by Bad Status',
    labels={'bad': 'Bad Status', 'value': 'Value', 'variable': 'Statistic'},
    category_orders={"bad": [0, 1]}, # Ensure correct order
)
fig_debtinc_stats.update_xaxes(tickvals=[0, 1], ticktext=['Non-Defaulter', 'Defaulter'])

# Helper function for bad rate plots by categorical variable
def generate_bad_rate_plot(df, column_name):
    # Explicitly set observed=False to avoid FutureWarning with categorical data
    bad_rates_table = pd.pivot_table(
        df, values='custid', index=column_name, columns='bad',
        aggfunc='count', fill_value=0, observed=False
    )
    bad_rates_table['Total'] = bad_rates_table.sum(axis=1)
    bad_rates_table['Bad Rate'] = (bad_rates_table[1] / bad_rates_table['Total']) * 100

    fig = px.bar(
        bad_rates_table.reset_index(),
        x=column_name, y='Bad Rate',
        title=f'Bad Rate by {column_name.replace("_", " ").title()}',
        labels={'Bad Rate': 'Bad Rate (%)'},
        color_discrete_sequence=px.colors.qualitative.Plotly
    )
    fig.update_layout(title_x=0.5)
    return fig, bad_rates_table

# Pre-generate some key plots/data for easy access in callbacks
categorical_cols_for_eda = [
    'gender', 'ms', 'child', 'veh', 'house', 'selfemp',
    'account', 'deposit', 'preloan', 'age_category_cut'
]
numeric_cols_for_eda = [
    'debtinc', 'creddebt', 'othdebt'
]

# Heatmap for Gender and Marital Status
heatmap_gender_ms_data = data.pivot_table(index='gender', columns='ms', values='bad', aggfunc=lambda x: (x == 1).sum() / len(x) * 100, observed=False)
fig_heatmap_gender_ms = px.imshow(
    heatmap_gender_ms_data,
    text_auto=".2f",
    color_continuous_scale='Viridis',
    title='Bad Rate by Gender and Marital Status (%)'
)
fig_heatmap_gender_ms.update_layout(title_x=0.5)

# Heatmap for House and Child
bad_rate_house_child_data = data.groupby(['house', 'child'], observed=False)['bad'].value_counts(normalize=True).unstack() * 100
pivot_table_house_child = bad_rate_house_child_data.pivot_table(index='house', columns='child', values=1, observed=False) # Values=1 for 'Defaulter'
fig_heatmap_house_child = px.imshow(
    pivot_table_house_child,
    text_auto=".1f",
    color_continuous_scale='Viridis',
    title='Bad Rate by House and Child (%)'
)
fig_heatmap_house_child.update_layout(title_x=0.5)

# =====================================================
# FINAL PRECOMPUTED TEST RESULTS (LOCKED)
# =====================================================

model_results = {

    "Logistic Regression": {
        "auc": 0.65,
        "confusion_matrix": [[853, 361],
                             [88, 97]],
        "classification_report": {
            "0 (Good)": {"precision": 0.91, "recall": 0.70, "f1": 0.79},
            "1 (Bad)":  {"precision": 0.21, "recall": 0.52, "f1": 0.30}
        }
    },

    "Naive Bayes": {
        "auc": 0.67,
        "confusion_matrix": [[757, 438],
                             [75, 129]],
        "classification_report": {
            "0 (Good)": {"precision": 0.91, "recall": 0.63, "f1": 0.75},
            "1 (Bad)":  {"precision": 0.57, "recall": 0.63, "f1": 0.33}
        }
    },

    "Decision Tree": {
        "auc": 0.84,
        "confusion_matrix": [[918, 277],
                             [47, 157]],
        "classification_report": {
            "0 (Good)": {"precision": 0.95, "recall": 0.77, "f1": 0.85},
            "1 (Bad)":  {"precision": 0.36, "recall": 0.77, "f1": 0.49}
        }
    },

    "Random Forest": {
        "auc": 0.80,
        "confusion_matrix": [[1080, 134],
                             [106, 79]],
        "classification_report": {
            "0 (Good)": {"precision": 0.91, "recall": 0.70, "f1": 0.79},
            "1 (Bad)":  {"precision": 0.21, "recall": 0.52, "f1": 0.30}
        }
    },

    "XGBoost": {
        "auc": 0.78,
        "confusion_matrix": [[899, 315],
                             [48, 137]],
        "classification_report": {
            "0 (Good)": {"precision": 0.88, "recall": 1.00, "f1": 0.93},
            "1 (Bad)":  {"precision": 0.78, "recall": 0.10, "f1": 0.17}
        }
    },

    "SVM": {
        "auc": 0.72,
        "confusion_matrix": [[790, 423],
                             [65, 120]],
        "classification_report": {
            "0 (Good)": {"precision": 0.91, "recall": 0.70, "f1": 0.79},
            "1 (Bad)":  {"precision": 0.21, "recall": 0.52, "f1": 0.30}
        }
    }
}

# -------- AUTO BEST MODEL DETECTION --------
best_model_name = max(
    model_results.keys(),
    key=lambda m: model_results[m]["auc"]
)

best_model_auc = model_results[best_model_name]["auc"]

# --- 4. KPI Calculations (for top section of dashboard) ---
total_customers = len(data)
defaulter_count = data[data['bad'] == 1].shape[0]
non_defaulter_count = data[data['bad'] == 0].shape[0]
defaulter_rate = (defaulter_count / total_customers) * 100
non_defaulter_rate = (non_defaulter_count / total_customers) * 100

# --- 5. Sentiment Analysis ---
with open('NPS Survey.txt', 'r') as file:
    nps_survey_text = file.read()

sia = SentimentIntensityAnalyzer()
def get_sentiment(text):
    score = sia.polarity_scores(text)["compound"]
    if score >= 0.05:
        return "Positive"
    elif score <= -0.05:
        return "Negative"
    else:
        return "Neutral"

nps_comments = [line.strip() for line in nps_survey_text.split('\n') if line.strip()]
nps_df = pd.DataFrame(nps_comments, columns=["Review"])
nps_df["Sentiment"] = nps_df["Review"].apply(get_sentiment)

# Prepare sentiment counts DataFrame with explicit column names for px.pie
sentiment_counts_df = nps_df['Sentiment'].value_counts().reset_index()
sentiment_counts_df.columns = ['SentimentCategory', 'Count'] # Explicitly rename columns

# ---------- FEEDBACK KPI CALCULATIONS ----------
total_reviews = len(nps_df)

positive_count = sentiment_counts_df.loc[
    sentiment_counts_df['SentimentCategory'] == 'Positive', 'Count'
].sum()

negative_count = sentiment_counts_df.loc[
    sentiment_counts_df['SentimentCategory'] == 'Negative', 'Count'
].sum()

positive_pct = (positive_count / total_reviews) * 100 if total_reviews > 0 else 0
negative_pct = (negative_count / total_reviews) * 100 if total_reviews > 0 else 0

# Generate Word Cloud
all_reviews_text_wc = ' '.join(nps_df['Review'].astype(str))
stop_words_wc = set(stopwords.words('english'))
custom_stopwords_wc = ['bank', 'loan', 'process'] # Words to exclude
stop_words_wc.update(custom_stopwords_wc)
processed_reviews_wc = " ".join([word for word in all_reviews_text_wc.split() if word.lower() not in stop_words_wc and word.isalpha()])
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(processed_reviews_wc)
buf = io.BytesIO()
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title('Word Cloud of Customer Reviews')
plt.savefig(buf, format='png')
plt.close() # Close the plot to prevent it from displaying twice
data_uri = base64.b64encode(buf.getbuffer()).decode("utf8")
wordcloud_img_src = f"data:image/png;base64,{data_uri}"

# -------- LOAD DECISION TREE IMAGE --------
import base64

with open("decision_tree.png", "rb") as f:
    decision_tree_encoded = base64.b64encode(f.read()).decode()

with open("feature_importance.png", "rb") as f:
    feature_importance_encoded = base64.b64encode(f.read()).decode()

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# -------- FEATURE MATRIX FOR MODEL --------

# Select numeric variables for modelling
feature_columns = ['debtinc', 'creddebt', 'othdebt']

X = data[feature_columns]
y = data['bad']

# Handle missing numeric values
X = X.fillna(0)

# -------- TRAIN RANDOM FOREST MODEL --------

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X, y)




# --- 6. Dash Application Initialization and Layout ---
app = Dash(__name__) # Corrected initialization: Dash class imported directly
server = app.server   #deployment
app.title = "Bank Credit Risk Dashboard"

# ---------- CSS STYLING (ADD EXACTLY HERE) ----------
app.index_string = """
<!DOCTYPE html>
<html>
    <head>
        {%metas%}
        <title>{%title%}</title>
        {%favicon%}
        {%css%}
        <!-- FONT AWESOME ICONS -->
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          rel="stylesheet"
        />

        <style>
            body {
                font-family: "Segoe UI", Arial, sans-serif;
                background-color: #f4f6f9;
                margin: 0;
                padding: 0;
            }

            h1, h2, h3 {
                font-weight: 600;
            }

            .kpi-card {
                background: white;
                border-radius: 10px;
                box-shadow: 0 4px 10px rgba(0,0,0,0.08);
                padding: 20px;
                text-align: center;          /* 👈 ADD THIS */
            }

            .graph-container {
                background: white;
                border-radius: 10px;
                padding: 15px;
                box-shadow: 0 4px 10px rgba(0,0,0,0.08);
                margin-bottom: 20px;
            }

            .dash-tabs {
                background: white;
                border-radius: 10px;
                padding: 10px;
                box-shadow: 0 2px 6px rgba(0,0,0,0.06);
            }

            th {
                background-color: #1f4ed8;
                color: white;
                padding: 10px;
            }

            td {
                padding: 8px;
                border: 1px solid #e5e7eb;
            }
            .sidebar {
                width: 240px;
                transition: width 0.3s ease;
            }

            .sidebar.collapsed {
                width: 70px;
            }

            .sidebar .tab {
                padding: 14px;
                font-weight: 500;
                display: flex;
                align-items: center;
                gap: 12px;
            }

            .sidebar .tab--selected {
                background-color: #1f4ed8;
                color: white;
                border-radius: 8px;
                transition: background-color 0.3s ease;
            }

            .sidebar i {
                font-size: 18px;
            }

            .toggle-btn {
                text-align: center;
                cursor: pointer;
                margin-bottom: 15px;
                font-size: 18px;
            }

            .content-area {
                flex-grow: 1;
                padding: 25px;
                background-color: #f4f6f9;
            }

            /* -------- TAB 2 – MODEL PERFORMANCE STYLING -------- */

            .model-card {
                background: white;
                border-radius: 12px;
                padding: 20px;
                box-shadow: 0 6px 14px rgba(0,0,0,0.08);
            }

            .auc-box {
                background: #eef2ff;
                border-radius: 10px;
                padding: 15px;
                text-align: center;
                margin-bottom: 15px;
            }

            .auc-box h1 {
                color: #1f4ed8;
                font-size: 36px;
                margin: 5px 0;
            }

            .section-title {
                font-weight: 600;
                margin-bottom: 10px;
                color: #1f2937;
                text-align: center;
            }

            .visual-box {
                margin-top: 20px;
                padding: 15px;
                border-radius: 10px;
                background: #f9fafb;
            }

            .dropdown-box {
                width: 300px;
                margin: 0 auto 25px auto;
            }
/* -------- BEST MODEL HIGHLIGHT -------- */
            .best-model-badge {
                background: linear-gradient(135deg, #22c55e, #16a34a);
                color: white;
                padding: 8px 14px;
                border-radius: 20px;
                font-size: 13px;
                font-weight: 600;
                display: inline-block;
                margin-left: 10px;
            }

            .best-model-box {
                background: #ecfdf5;
                border-left: 6px solid #22c55e;
                padding: 12px;
                border-radius: 8px;
                margin-bottom: 15px;
                text-align: center;
                font-weight: 600;
                color: #065f46;
            }

        </style>
    </head>
    <body>
        {%app_entry%}
        <footer>
            {%config%}
            {%scripts%}
            {%renderer%}
        </footer>
    </body>
</html>
"""
# ---------- END CSS ----------

# Define the content for the 'Customer Trends' tab
tab_1_layout = html.Div([
    html.H2("Customer Demographics and Loan Behavior Trends", style={'textAlign': 'center', 'color': '#000080', 'font-family': 'Arial, sans-serif'}),

    # New selection mechanism for EDA plot type
    html.Div([
        html.Label("Select Plot Type:", style={'font-weight': 'bold', 'color': '#696969', 'margin-right': '10px'}),
        dcc.RadioItems(
            id='eda-plot-type-selector',
            options=[
                {'label': 'Categorical Bad Rate', 'value': 'categorical_bad_rate'},
                {'label': 'Numeric Box-Whisker', 'value': 'numeric_box_whisker'},
                {'label': 'Numeric Mean/Median', 'value': 'numeric_mean_median'},
                {'label': 'Heatmap', 'value': 'heatmap'}
            ],
            value='categorical_bad_rate', # Default selection
            inline=True,
            labelStyle={'margin-right': '25px'}
        ),
    ], style={'textAlign': 'center', 'margin': '20px 0'}),

    # New selection mechanism for specific variable/heatmap type
    html.Div([
        html.Label("Select Variable/Heatmap:", style={'font-weight': 'bold', 'color': '#696969', 'margin-right': '10px'}),
        dcc.Dropdown(
            id='eda-variable-selector',
            options=[], # Options will be dynamically populated
            value=None, # No default value initially
            clearable=False,
            style={'width': '50%', 'margin': '10px auto'}
        )
    ], style={'textAlign': 'center', 'margin': '20px 0'}),

    html.Div([
        # Graph for the selected EDA plot
        dcc.Graph(id='eda-main-graph', style={'width': '100%', 'height': '600px'})
    ])
])

# -------------------------
# TAB 2 – MODEL PERFORMANCE (ATTRACTIVE VERSION)
# -------------------------
tab_2_layout = html.Div(
    style={"padding": "30px"},
    children=[

        html.H2(
            "Model Performance Evaluation",
            style={"textAlign": "center", "marginBottom": "25px"}
        ),

        html.Div(
            className="dropdown-box",
            children=[
                html.Label("Select Model", style={"fontWeight": "600"}),
                dcc.Dropdown(
                    id="model-dropdown",
                    options=[{"label": m, "value": m} for m in model_results.keys()],
                    value="Decision Tree",
                    clearable=False
                )
            ]
        ),

        html.Div(
            style={"display": "flex", "gap": "30px"},
            children=[

                # -------- LEFT PANEL --------
                html.Div(
                    className="model-card",
                    style={"flex": "1"},
                    children=[

                        html.H3(id="model-title", style={"textAlign": "center"}),

                        html.Div(id="best-model-indicator",className="best-model-box"),

                        html.Div(
                            className="auc-box",
                            children=[
                                html.P("AUC Score (TEST DATA)", style={"fontWeight": "600"}),
                                html.H1(id="auc-value")
                            ]
                        ),

                        html.H4("Classification Report", className="section-title"),
                        html.Div(id="classification-table"),

                        html.Div(
                            id="model-left-visual",
                            className="visual-box"
                        )
                    ]
                ),

                # -------- RIGHT PANEL --------
                html.Div(
                    className="model-card",
                    style={"flex": "1"},
                    children=[
                        html.H4("Confusion Matrix", className="section-title"),
                        dcc.Graph(id="confusion-matrix"),

                        html.Div(
                            id="model-extra-visual",
                            className="visual-box"
                        )
                    ]
                )
            ]
        )
    ]
)


# -------------------------
# APP LAYOUT
# -------------------------
app.layout = html.Div([

    html.H1(
        "Bank Loan Default Prediction Dashboard",
        style={"textAlign": "center"}
    ),

    dcc.Tabs(
        value="model",
        children=[
            dcc.Tab(label="Model Performance", value="model")
        ]
    ),

    html.Div(id="tab-content")
])

# Define the content for the 'Customer Feedback' tab
# ================= CUSTOMER FEEDBACK TAB =================
tab_3_layout = html.Div([

    html.H2(
        "Customer Feedback Analysis (NPS Survey)",
        style={'textAlign': 'center', 'color': '#000080'}
    ),

    # -------- FEEDBACK KPIs --------
    html.Div([
        html.Div([
            html.H4("Positive Feedback"),
            html.P(f"{positive_pct:.2f}%", style={'fontSize': 26, 'color': '#16a34a', 'fontWeight': 'bold'})
        ], className="kpi-card"),

        html.Div([
            html.H4("Negative Feedback"),
            html.P(f"{negative_pct:.2f}%", style={'fontSize': 26, 'color': '#dc2626', 'fontWeight': 'bold'})
        ], className="kpi-card"),

        html.Div([
            html.H4("Total Feedback"),
            html.P(f"{total_reviews}", style={'fontSize': 26, 'color': '#2563eb', 'fontWeight': 'bold'})
        ], className="kpi-card"),
    ], style={
        'display': 'grid',
        'gridTemplateColumns': 'repeat(3, 1fr)',
        'gap': '20px',
        'margin': '20px'
    }),

    # -------- PIE + WORD CLOUD --------
    html.Div([

        html.Div([
            dcc.Graph(
                figure=px.pie(
                    sentiment_counts_df,
                    names='SentimentCategory',
                    values='Count',
                    title='Customer Sentiment Distribution',
                    color_discrete_sequence=px.colors.qualitative.Pastel
                )
            )
        ], className="graph-container", style={'width': '48%'}),

        html.Div([
            html.H4("Customer Feedback Word Cloud", style={'textAlign': 'center'}),
            html.Img(
                id='dynamic-wordcloud',
                src=wordcloud_img_src,
                style={'width': '100%'}
)

        ], className="graph-container", style={'width': '48%'})

    ], style={'display': 'flex', 'justifyContent': 'space-between'}),

     # -------- SENTIMENT FILTER --------
    html.Div([
        html.Label("Filter Feedback by Sentiment:", style={'fontWeight': 'bold'}),
        dcc.Dropdown(
            id='sentiment-filter',
            options=[
                {'label': 'All', 'value': 'All'},
                {'label': 'Positive', 'value': 'Positive'},
                {'label': 'Neutral', 'value': 'Neutral'},
                {'label': 'Negative', 'value': 'Negative'}
            ],
            value='All',
            clearable=False,
            style={'width': '300px'}
        )
    ], style={'textAlign': 'center', 'marginBottom': '20px'}),

    # -------- FEEDBACK TABLE --------
    html.Div([
        html.H3("Sample Customer Feedback (Top 10)", style={'textAlign': 'center'}),

        dash_table.DataTable(
            id='feedback-table',
            columns=[
                {"name": "Review", "id": "Review"},
                {"name": "Sentiment", "id": "Sentiment"}
            ],
            data=nps_df.head(10).to_dict('records'),
            style_table={'overflowX': 'auto'},
            style_cell={'textAlign': 'left', 'padding': '8px'},
            style_header=
                {
                'backgroundColor': '#1f4ed8',
                'color': 'white',
                'fontWeight': 'bold'
            }
        )
    ], className="graph-container", style={'marginTop': '20px'}),

    # -------- INSIGHT BOX --------
    html.Div(
        "Majority of customers express positive sentiment towards loan processing and service quality. "
        "Negative feedback mainly highlights delays and documentation issues, indicating areas for operational improvement.",
        style=
            {
            'background': '#ecfeff',
            'padding': '15px',
            'borderRadius': '10px',
            'marginTop': '20px',
            'textAlign': 'center',
            'fontWeight': '500'
        }
    )

])

# -------- AUC SCORES FOR MODEL COMPARISON --------
auc_scores_dashboard = {
    'Logistic Regression': 0.65,
    'Naive Bayes': 0.67,
    'Decision Tree': 0.84,
    'Random Forest': 0.83,
    'XGBoost': 0.78,
    'SVM': 0.61
}

# Define the content for the 'Model Comparison' tab
tab_4_layout = html.Div([

    html.H2(
        "Model Comparison Summary",
        style={'textAlign': 'center', 'color': '#000080'}
    ),

    # -------- AUC BAR CHART --------
    html.Div([
   dcc.Graph(
    figure=px.bar(
        x=list(auc_scores_dashboard.keys()),
        y=list(auc_scores_dashboard.values()),
        labels={'x': 'Machine Learning Model', 'y': 'AUC Score'},
        title='AUC Comparison Across Models',
        text=[f"{v:.2f}" for v in auc_scores_dashboard.values()],
        color=[
            "Best Model" if m == "Decision Tree" else "Other"
            for m in auc_scores_dashboard.keys()
            ],
        color_discrete_map={
            "Best Model": "#16a34a",
            "Other": "#3b82f6"
            },
        color_continuous_scale="Blues"
    )
    .update_traces(
        textposition='outside',
        cliponaxis=False,
        marker_line_width=1.5,
        marker_line_color="black"
    )
    .update_layout(
        title_x=0.5,
        height=600,                    # bigger vertical space
        margin=dict(t=120, b=60),      # extra space top and bottom
        plot_bgcolor="white",
        paper_bgcolor="white",
        yaxis=dict(
            range=[0, max(auc_scores_dashboard.values()) * 1.25],
            title="AUC Score"
        ),
        xaxis=dict(
            title="Model"
        ),
        font=dict(size=14)
    )
)
    ], className="graph-container"),

    # -------- PERFORMANCE TABLE (DEFaULTER CLASS) --------
    html.Div([
        html.H3("Defaulter (Class 1) Performance Metrics", style={'textAlign': 'center'}),

        dash_table.DataTable(
            columns=[
                {"name": "Model", "id": "Model"},
                {"name": "AUC", "id": "AUC"},
                {"name": "Precision", "id": "Precision"},
                {"name": "Recall", "id": "Recall"}

            ],
            data=[
                {
                    "Model": model,
                    "AUC": f"{vals['auc']:.2f}",
                    "Precision": f"{vals['classification_report']['1 (Bad)']['precision']:.2f}",
                    "Recall": f"{vals['classification_report']['1 (Bad)']['recall']:.2f}",

                }
                for model, vals in model_results.items()
            ],
            style_table={'overflowX': 'auto'},
            style_cell={'padding': '8px', 'textAlign': 'center'},
            style_header={
                'backgroundColor': '#1f4ed8',
                'color': 'white',
                'fontWeight': 'bold'
            }
        )
    ], className="graph-container", style={'marginTop': '20px'})
])

# ================= SMOTE ANALYSIS =================


# Use KPI values to keep numbers consistent
before_non_defaulter = non_defaulter_count
before_defaulter = defaulter_count

# After SMOTE → balanced dataset
after_non_defaulter = non_defaulter_count
after_defaulter = non_defaulter_count

smote_df = pd.DataFrame({
    "Class": ["Non-Defaulter", "Defaulter"],
    "Before SMOTE": [before_non_defaulter, before_defaulter],
    "After SMOTE": [after_non_defaulter, after_defaulter]
})

# -------- Calculate percentages --------
total_before = smote_df["Before SMOTE"].sum()
total_after = smote_df["After SMOTE"].sum()

smote_df["Before %"] = (smote_df["Before SMOTE"] / total_before * 100).round(1)
smote_df["After %"] = (smote_df["After SMOTE"] / total_after * 100).round(1)

# -------- Improved SMOTE visualization --------
fig_smote_distribution = px.bar(
    smote_df,
    x="Class",
    y=["Before SMOTE", "After SMOTE"],
    barmode="group",
    title="Class Distribution Before vs After SMOTE (Handling Class Imbalance)",
    labels={"value": "Number of Customers", "variable": "Dataset"}
)

# Add percentage labels above bars
fig_smote_distribution.update_traces(
    textposition="outside",
    cliponaxis=False
)

fig_smote_distribution.data[0].text = [
    f"{v} ({p}%)"
    for v, p in zip(smote_df["Before SMOTE"], smote_df["Before %"])
]

fig_smote_distribution.data[1].text = [
    f"{v} ({p}%)"
    for v, p in zip(smote_df["After SMOTE"], smote_df["After %"])
]

fig_smote_distribution.update_layout(
    title_x=0.5,
    height=650,              # increases chart height
    margin=dict(t=120),      # adds space above bars
    yaxis=dict(
        title="Number of Customers",
        range=[0, max(smote_df["Before SMOTE"].max(), smote_df["After SMOTE"].max()) * 1.25]
    )
)

tab_5_layout = html.Div([

    html.H2(
        "Class Imbalance Handling using SMOTE",
        style={'textAlign': 'center', 'color': '#000080'}
    ),

    html.Div([
        dcc.Graph(figure=fig_smote_distribution)
    ], className="graph-container"),

    html.Div(
        "Before SMOTE, only about 13% of customers were defaulters. "
        "SMOTE balances the dataset by generating synthetic defaulter samples, "
        "resulting in equal representation of both classes and improving model learning.",
        style={
            'background': '#ecfeff',
            'padding': '15px',
            'borderRadius': '10px',
            'marginTop': '20px',
            'textAlign': 'center'
        }
    )

])

app.layout = html.Div([
    # Dashboard Title
    html.H1("Bank Loan Default Prediction Dashboard", style={'textAlign': 'center', 'color': '#000080', 'font-family': 'Arial, sans-serif'}),

    # KPI Section
html.Div([
    html.Div([
        html.H3("Defaulter Rate"),
        html.P(f"{defaulter_rate:.2f}%", style=
            {
            'fontSize': 28,
            'color': '#dc2626',
            'fontWeight': 'bold'
        })
    ], className="kpi-card"),

    html.Div([
        html.H3("Non-Defaulter Rate"),
        html.P(f"{non_defaulter_rate:.2f}%", style=
            {
            'fontSize': 28,
            'color': '#16a34a',
            'fontWeight': 'bold'
        })
    ], className="kpi-card"),

    html.Div([
        html.H3("Total Customers"),
        html.P(f"{total_customers}", style=
            {
            'fontSize': 28,
            'color': '#2563eb',
            'fontWeight': 'bold'
        })
    ], className="kpi-card"),
], style=
    {
    'display': 'grid',
    'gridTemplateColumns': 'repeat(3, 1fr)',
    'gap': '20px',
    'margin': '20px'
}),

html.Div(
    "Insight: Approximately 13% of customers default, indicating strong class imbalance and the need for robust models.",
    style=
        {
        'textAlign': 'center',
        'background': '#ecfeff',
        'padding': '12px',
        'borderRadius': '8px',
        'margin': '10px 20px'
    }
),

html.Div([

    # ---------- SIDEBAR ----------
    html.Div(
        id="sidebar",
        className="sidebar",
        children=[

            html.Div(
                html.I(className="fas fa-bars"),
                id="sidebar-toggle",
                className="toggle-btn"
            ),
            dcc.Tabs(
                id="dashboard-tabs",
                value="tab-1-customer-trends",
                vertical=True,
                className="dash-tabs",
                children=[

                    dcc.Tab(
                        label="Customer Trends",
                        value="tab-1-customer-trends",
                        className="tab",
                        selected_className="tab--selected"
                    ),

                    dcc.Tab(
                        label="Model Performance",
                        value="tab-2-model-performance",
                        className="tab",
                        selected_className="tab--selected"
                    ),

                    dcc.Tab(
                        label="Model Comparison",
                        value="tab-4-model-comparison",
                        className="tab",
                        selected_className="tab--selected"
                    ),

                    dcc.Tab(
                        label="Customer Feedback",
                        value="tab-3-customer-feedback",
                        className="tab",
                        selected_className="tab--selected"
                    ),
                    dcc.Tab(
                        label="SMOTE Analysis",
                        value="tab-5-smote-analysis",
                        className="tab",
                        selected_className="tab--selected"
                        ),

    ]
)

        ],
        style=
            {
            'background': 'white',
            'boxShadow': '2px 0px 6px rgba(0,0,0,0.1)',
            'minHeight': '100vh'
        }
    ),

    # ---------- MAIN CONTENT ----------
    html.Div(
        id='tabs-content-display',
        className="content-area"
    )

], style={'display': 'flex'})

])
#tab 2 model performance
html.Div(
    children=[

        dcc.Tabs(
            value="tab-1",
            children=[

                dcc.Tab(
                    label="Overview",
                    value="tab-1",
                    children=[
                        html.Div(
                            style={"padding": "30px"},
                            children=[
                                html.H2("Project Overview"),
                                html.P(
                                    "This tab can contain EDA, dataset summary, "
                                    "business objective, or customer trends."
                                )
                            ]
                        )
                    ]
                ),

                dcc.Tab(
                    label="Model Performance",
                    value="tab-2",
                    children=tab_2_layout
                )
            ]
        )
    ]
)

# --- 7. Callbacks ---
@app.callback(Output('tabs-content-display', 'children'),
              Input('dashboard-tabs', 'value'))
def render_tab_content(tab_name):
    if tab_name == 'tab-1-customer-trends':
        return tab_1_layout
    elif tab_name == 'tab-2-model-performance':
        return tab_2_layout
    elif tab_name == 'tab-4-model-comparison':
        return tab_4_layout
    elif tab_name == 'tab-3-customer-feedback':
        return tab_3_layout
    elif tab_name == 'tab-5-smote-analysis':
      return tab_5_layout
    return html.Div([html.H3("Select a tab to view content")])

# Callback to update options in eda-variable-selector based on plot type selection
@app.callback(
    Output('eda-variable-selector', 'options'),
    Input('eda-plot-type-selector', 'value')
)
def set_eda_variable_options(selected_plot_type):
    options = []
    if selected_plot_type == 'categorical_bad_rate':
        options = [{'label': col.replace('_', ' ').title(), 'value': col} for col in categorical_cols_for_eda]
    elif selected_plot_type == 'numeric_box_whisker' or selected_plot_type == 'numeric_mean_median':
        options = [{'label': col.replace('_', ' ').title(), 'value': col} for col in numeric_cols_for_eda]
    elif selected_plot_type == 'heatmap':
        options = [
            {'label': 'Gender vs Marital Status', 'value': 'gender_ms'},
            {'label': 'House vs Child', 'value': 'house_child'}

        ]
    return options

# Callback to update the main EDA graph
@app.callback(
    Output('eda-main-graph', 'figure'),
    Input('eda-plot-type-selector', 'value'),
    Input('eda-variable-selector', 'value')
)
def update_eda_graph(selected_plot_type, selected_variable):
    if not selected_variable:
        return go.Figure()

    fig = go.Figure()
    if selected_plot_type == 'categorical_bad_rate':
        fig, _ = generate_bad_rate_plot(data, selected_variable)
    elif selected_plot_type == 'numeric_box_whisker':
        # Create Box-Whisker plot for numeric variable by 'bad' status
        temp_data = data.dropna(subset=[selected_variable, 'bad'])
        fig = px.box(temp_data, x='bad', y=selected_variable,
                     title=f'Box-Whisker Plot of {selected_variable.replace("_", " ").title()} by Bad Status')
        fig.update_xaxes(tickvals=[0, 1], ticktext=['Non-Defaulter', 'Defaulter'])
        fig.update_layout(title_x=0.5)
    elif selected_plot_type == 'numeric_mean_median':
        # Calculate mean and median for numeric variable by 'bad' status
        temp_data = data.dropna(subset=[selected_variable, 'bad'])
        stats = temp_data.groupby('bad')[selected_variable].agg(['mean', 'median'])
        fig = px.bar(
            stats.reset_index(),
            x='bad', y=['mean', 'median'], barmode='group',
            title=f'Mean and Median of {selected_variable.replace("_", " ").title()} by Bad Status',
            labels={'bad': 'Bad Status', 'value': 'Value', 'variable': 'Statistic'}
        )
        fig.update_xaxes(tickvals=[0, 1], ticktext=['Non-Defaulter', 'Defaulter'])
        fig.update_layout(title_x=0.5)
    elif selected_plot_type == 'heatmap':
        if selected_variable == 'gender_ms':
            fig = fig_heatmap_gender_ms
        elif selected_variable == 'house_child':
            fig = fig_heatmap_house_child

    return fig

# Helper function for model metrics table
def get_cm_and_report_for_dash(model_id):
    model_data = model_performance_data[model_id]
    report = model_data['report']
    cm = model_data['cm']

    metrics_df = pd.DataFrame({
        'Metric': ['Precision (Class 0)', 'Recall (Class 0)', 'F1-Score (Class 0)',
                   'Precision (Class 1)', 'Recall (Class 1)', 'F1-Score (Class 1)',
                   'Accuracy', 'Macro Avg Precision', 'Macro Avg Recall', 'Macro Avg F1-Score',
                   'Weighted Avg Precision', 'Weighted Avg Recall', 'Weighted Avg F1-Score'],
        'Value': [
            f"{report['0']['precision']:.2f}",
            f"{report['0']['recall']:.2f}",
            f"{report['0']['f1-score']:.2f}",
            f"{report['1']['precision']:.2f}",
            f"{report['1']['recall']:.2f}",
            f"{report['1']['f1-score']:.2f}",
            f"{report['accuracy']:.2f}",
            f"{report['macro avg']['precision']:.2f}",
            f"{report['macro avg']['recall']:.2f}",
            f"{report['macro avg']['f1-score']:.2f}",
            f"{report['weighted avg']['precision']:.2f}",
            f"{report['weighted avg']['recall']:.2f}",
            f"{report['weighted avg']['f1-score']:.2f}"
        ]
    })

    metrics_table_html = html.Div([
        html.H3(f"Performance Metrics - {model_data['name']}", style={'textAlign': 'center', 'color': '#000080', 'font-family': 'Arial, sans-serif'}),
        dash_table.DataTable(
            id='table',
            columns=[{"name": i, "id": i} for i in metrics_df.columns],
            data=metrics_df.to_dict('records'),
            style_table={'overflowX': 'auto'},
            style_cell={'textAlign': 'left', 'padding': '5px'},
            style_header={'backgroundColor': 'rgb(230, 230, 230)', 'fontWeight': 'bold'}
        ),
        html.H4("Confusion Matrix", style={'textAlign': 'center', 'marginTop': '20px', 'color': '#000080', 'font-family': 'Arial, sans-serif'}),
        html.Table(
            # Header
            [html.Tr([html.Th(""), html.Th("Predicted 0"), html.Th("Predicted 1")])] +

            # Body
            [html.Tr([
                html.Th("Actual 0"), html.Td(cm[0][0]), html.Td(cm[0][1])
            ]),
            html.Tr([
                html.Th("Actual 1"), html.Td(cm[1][0]), html.Td(cm[1][1])
            ])],
            style={'width': '80%', 'margin': 'auto', 'borderCollapse': 'collapse', 'textAlign': 'center'},
            className='table table-bordered' # Added className for potential CSS styling
        )
    ])
    return metrics_table_html



# -------- SENTIMENT FILTER CALLBACK --------
@app.callback(
    Output('feedback-table', 'data'),
    Input('sentiment-filter', 'value')
)
def update_feedback_table(selected_sentiment):
    if selected_sentiment == 'All':
        return nps_df.head(10).to_dict('records')
    else:
        return nps_df[nps_df['Sentiment'] == selected_sentiment].head(10).to_dict('records')

@app.callback(
    Output('dynamic-wordcloud', 'src'),
    Input('sentiment-filter', 'value')
)
def update_wordcloud(selected_sentiment):

    # Filter reviews based on dropdown
    if selected_sentiment == 'All':
        filtered_df = nps_df
    else:
        filtered_df = nps_df[nps_df['Sentiment'] == selected_sentiment]

    # If no reviews, return empty image
    if filtered_df.empty:
        return wordcloud_img_src

    # Generate text for word cloud
    text = ' '.join(filtered_df['Review'].astype(str))

    stop_words_wc = set(stopwords.words('english'))
    stop_words_wc.update(['bank', 'loan', 'process'])

    processed_text = " ".join(
        word for word in text.split()
        if word.lower() not in stop_words_wc and word.isalpha()
    )

    wc = WordCloud(
        width=800,
        height=400,
        background_color='white'
    ).generate(processed_text)

    buf = io.BytesIO()
    plt.figure(figsize=(10, 5))
    plt.imshow(wc, interpolation='bilinear')
    plt.axis('off')
    plt.savefig(buf, format='png')
    plt.close()

    encoded_img = base64.b64encode(buf.getvalue()).decode()
    return f"data:image/png;base64,{encoded_img}"

@app.callback(
    Output("sidebar", "className"),
    Input("sidebar-toggle", "n_clicks"),
    State("sidebar", "className")
)
def toggle_sidebar(n_clicks, current_class):
    if n_clicks:
        if current_class and "collapsed" in current_class:
            return "sidebar"
        else:
            return "sidebar collapsed"
    return "sidebar"

# -------------------------
# CALLBACK (MODEL PERFORMANCE)
# -------------------------
@app.callback(
    Output("model-title", "children"),
    Output("best-model-indicator", "children"),
    Output("auc-value", "children"),
    Output("classification-table", "children"),
    Output("confusion-matrix", "figure"),
    Output("model-left-visual", "children"),  # 👈 ADD
    Output("model-extra-visual", "children"),  # 👈 RIGHT
    Input("model-dropdown", "value")
)

def update_dashboard(selected_model):

    data = model_results[selected_model]

    auc = f"{data['auc']:.4f}"

    rows = []
    for cls, metrics in data["classification_report"].items():
        rows.append({
            "Class": cls,
            "Precision": metrics["precision"],
            "Recall": metrics["recall"],
            "F1-Score": metrics["f1"]
        })

    df = pd.DataFrame(rows)

    table = html.Table(
        style={"width": "100%", "borderCollapse": "collapse"},
        children=[
            html.Thead(html.Tr([html.Th(col) for col in df.columns])),
            html.Tbody([
                html.Tr([html.Td(df.iloc[i][col]) for col in df.columns])
                for i in range(len(df))
            ])
        ]
    )

    cm = data["confusion_matrix"]

    fig = ff.create_annotated_heatmap(
        z=cm,
        x=["Predicted: 0", "Predicted: 1"],
        y=["Actual: 1", "Actual: 0"],
        colorscale="Blues",
        showscale=True
    )

    fig.update_layout(margin=dict(l=40, r=40, t=40, b=40))

    # -------- VISUAL PLACEHOLDERS --------
    left_visual_children = []

    # 👉 Decision Tree image
    if selected_model == "Decision Tree":
        left_visual_children.append(
            html.Div([
                html.H4("Decision Tree Structure", style={"textAlign": "center"}),
                html.Img(
                    src=f"data:image/png;base64,{decision_tree_encoded}",
                    style={"width": "100%", "marginBottom": "20px"}
                )
            ])
        )

    # 👉 Random Forest feature importance
    if selected_model == "Random Forest":
        left_visual_children.append(
            html.Div([
                html.H4("Random Forest Feature Importance", style={"textAlign": "center"}),
                html.Img(
                    src=f"data:image/png;base64,{feature_importance_encoded}",
                    style={
                        "width": "100%",
                        "height": "auto",
                        "maxHeight": "450px",
                        "objectFit": "contain",
                        "display": "block",
                        "margin": "0 auto"
                    }
                )
            ])
        )

    left_visual = html.Div(left_visual_children)
    right_visual = html.Div()

    # -------- BEST MODEL TAG --------
    if selected_model == best_model_name:
        best_tag = html.Div([
            "BEST MODEL",
            html.Span(" ⭐", style={"marginLeft": "5px"})
        ])
    else:
        best_tag = f"Best Model: {best_model_name} (AUC = {best_model_auc:.2f})"

    return (
        f"{selected_model} Performance",
        best_tag,
        auc,
        table,
        fig,
        left_visual,
        right_visual
    )


if __name__ == "__main__":
    app.run_server(host="0.0.0.0", port=10000)
